
export interface TimezoneOption {
  value: string;
  label: string;
  city: string;
  offset: string;
  region: string;
}

// Main canonical IANA timezones (~140 zones)
export const timezoneOptions: TimezoneOption[] = [
  // Africa
  { value: "Africa/Abidjan", label: "Africa/Abidjan (UTC+00:00)", city: "Abidjan", offset: "UTC+00:00", region: "Africa" },
  { value: "Africa/Accra", label: "Africa/Accra (UTC+00:00)", city: "Accra", offset: "UTC+00:00", region: "Africa" },
  { value: "Africa/Addis_Ababa", label: "Africa/Addis_Ababa (UTC+03:00)", city: "Addis Ababa", offset: "UTC+03:00", region: "Africa" },
  { value: "Africa/Algiers", label: "Africa/Algiers (UTC+01:00)", city: "Algiers", offset: "UTC+01:00", region: "Africa" },
  { value: "Africa/Asmara", label: "Africa/Asmara (UTC+03:00)", city: "Asmara", offset: "UTC+03:00", region: "Africa" },
  { value: "Africa/Bamako", label: "Africa/Bamako (UTC+00:00)", city: "Bamako", offset: "UTC+00:00", region: "Africa" },
  { value: "Africa/Bangui", label: "Africa/Bangui (UTC+01:00)", city: "Bangui", offset: "UTC+01:00", region: "Africa" },
  { value: "Africa/Banjul", label: "Africa/Banjul (UTC+00:00)", city: "Banjul", offset: "UTC+00:00", region: "Africa" },
  { value: "Africa/Bissau", label: "Africa/Bissau (UTC+00:00)", city: "Bissau", offset: "UTC+00:00", region: "Africa" },
  { value: "Africa/Blantyre", label: "Africa/Blantyre (UTC+02:00)", city: "Blantyre", offset: "UTC+02:00", region: "Africa" },
  { value: "Africa/Brazzaville", label: "Africa/Brazzaville (UTC+01:00)", city: "Brazzaville", offset: "UTC+01:00", region: "Africa" },
  { value: "Africa/Bujumbura", label: "Africa/Bujumbura (UTC+02:00)", city: "Bujumbura", offset: "UTC+02:00", region: "Africa" },
  { value: "Africa/Cairo", label: "Africa/Cairo (UTC+02:00)", city: "Cairo", offset: "UTC+02:00", region: "Africa" },
  { value: "Africa/Casablanca", label: "Africa/Casablanca (UTC+01:00)", city: "Casablanca", offset: "UTC+01:00", region: "Africa" },
  { value: "Africa/Ceuta", label: "Africa/Ceuta (UTC+01:00)", city: "Ceuta", offset: "UTC+01:00", region: "Africa" },
  { value: "Africa/Conakry", label: "Africa/Conakry (UTC+00:00)", city: "Conakry", offset: "UTC+00:00", region: "Africa" },
  { value: "Africa/Dakar", label: "Africa/Dakar (UTC+00:00)", city: "Dakar", offset: "UTC+00:00", region: "Africa" },
  { value: "Africa/Dar_es_Salaam", label: "Africa/Dar_es_Salaam (UTC+03:00)", city: "Dar es Salaam", offset: "UTC+03:00", region: "Africa" },
  { value: "Africa/Djibouti", label: "Africa/Djibouti (UTC+03:00)", city: "Djibouti", offset: "UTC+03:00", region: "Africa" },
  { value: "Africa/Douala", label: "Africa/Douala (UTC+01:00)", city: "Douala", offset: "UTC+01:00", region: "Africa" },
  { value: "Africa/El_Aaiun", label: "Africa/El_Aaiun (UTC+01:00)", city: "El Aaiun", offset: "UTC+01:00", region: "Africa" },
  { value: "Africa/Freetown", label: "Africa/Freetown (UTC+00:00)", city: "Freetown", offset: "UTC+00:00", region: "Africa" },
  { value: "Africa/Gaborone", label: "Africa/Gaborone (UTC+02:00)", city: "Gaborone", offset: "UTC+02:00", region: "Africa" },
  { value: "Africa/Harare", label: "Africa/Harare (UTC+02:00)", city: "Harare", offset: "UTC+02:00", region: "Africa" },
  { value: "Africa/Johannesburg", label: "Africa/Johannesburg (UTC+02:00)", city: "Johannesburg", offset: "UTC+02:00", region: "Africa" },
  { value: "Africa/Juba", label: "Africa/Juba (UTC+03:00)", city: "Juba", offset: "UTC+03:00", region: "Africa" },
  { value: "Africa/Kampala", label: "Africa/Kampala (UTC+03:00)", city: "Kampala", offset: "UTC+03:00", region: "Africa" },
  { value: "Africa/Khartoum", label: "Africa/Khartoum (UTC+02:00)", city: "Khartoum", offset: "UTC+02:00", region: "Africa" },
  { value: "Africa/Kigali", label: "Africa/Kigali (UTC+02:00)", city: "Kigali", offset: "UTC+02:00", region: "Africa" },
  { value: "Africa/Kinshasa", label: "Africa/Kinshasa (UTC+01:00)", city: "Kinshasa", offset: "UTC+01:00", region: "Africa" },
  { value: "Africa/Lagos", label: "Africa/Lagos (UTC+01:00)", city: "Lagos", offset: "UTC+01:00", region: "Africa" },
  { value: "Africa/Libreville", label: "Africa/Libreville (UTC+01:00)", city: "Libreville", offset: "UTC+01:00", region: "Africa" },
  { value: "Africa/Lome", label: "Africa/Lome (UTC+00:00)", city: "Lome", offset: "UTC+00:00", region: "Africa" },
  { value: "Africa/Luanda", label: "Africa/Luanda (UTC+01:00)", city: "Luanda", offset: "UTC+01:00", region: "Africa" },
  { value: "Africa/Lubumbashi", label: "Africa/Lubumbashi (UTC+02:00)", city: "Lubumbashi", offset: "UTC+02:00", region: "Africa" },
  { value: "Africa/Lusaka", label: "Africa/Lusaka (UTC+02:00)", city: "Lusaka", offset: "UTC+02:00", region: "Africa" },
  { value: "Africa/Malabo", label: "Africa/Malabo (UTC+01:00)", city: "Malabo", offset: "UTC+01:00", region: "Africa" },
  { value: "Africa/Maputo", label: "Africa/Maputo (UTC+02:00)", city: "Maputo", offset: "UTC+02:00", region: "Africa" },
  { value: "Africa/Maseru", label: "Africa/Maseru (UTC+02:00)", city: "Maseru", offset: "UTC+02:00", region: "Africa" },
  { value: "Africa/Mbabane", label: "Africa/Mbabane (UTC+02:00)", city: "Mbabane", offset: "UTC+02:00", region: "Africa" },
  { value: "Africa/Mogadishu", label: "Africa/Mogadishu (UTC+03:00)", city: "Mogadishu", offset: "UTC+03:00", region: "Africa" },
  { value: "Africa/Monrovia", label: "Africa/Monrovia (UTC+00:00)", city: "Monrovia", offset: "UTC+00:00", region: "Africa" },
  { value: "Africa/Nairobi", label: "Africa/Nairobi (UTC+03:00)", city: "Nairobi", offset: "UTC+03:00", region: "Africa" },
  { value: "Africa/Ndjamena", label: "Africa/Ndjamena (UTC+01:00)", city: "Ndjamena", offset: "UTC+01:00", region: "Africa" },
  { value: "Africa/Niamey", label: "Africa/Niamey (UTC+01:00)", city: "Niamey", offset: "UTC+01:00", region: "Africa" },
  { value: "Africa/Nouakchott", label: "Africa/Nouakchott (UTC+00:00)", city: "Nouakchott", offset: "UTC+00:00", region: "Africa" },
  { value: "Africa/Ouagadougou", label: "Africa/Ouagadougou (UTC+00:00)", city: "Ouagadougou", offset: "UTC+00:00", region: "Africa" },
  { value: "Africa/Porto-Novo", label: "Africa/Porto-Novo (UTC+01:00)", city: "Porto-Novo", offset: "UTC+01:00", region: "Africa" },
  { value: "Africa/Sao_Tome", label: "Africa/Sao_Tome (UTC+00:00)", city: "Sao Tome", offset: "UTC+00:00", region: "Africa" },
  { value: "Africa/Tripoli", label: "Africa/Tripoli (UTC+02:00)", city: "Tripoli", offset: "UTC+02:00", region: "Africa" },
  { value: "Africa/Tunis", label: "Africa/Tunis (UTC+01:00)", city: "Tunis", offset: "UTC+01:00", region: "Africa" },
  { value: "Africa/Windhoek", label: "Africa/Windhoek (UTC+02:00)", city: "Windhoek", offset: "UTC+02:00", region: "Africa" },

  // America
  { value: "America/Adak", label: "America/Adak (UTC-10:00)", city: "Adak", offset: "UTC-10:00", region: "America" },
  { value: "America/Anchorage", label: "America/Anchorage (UTC-09:00)", city: "Anchorage", offset: "UTC-09:00", region: "America" },
  { value: "America/Anguilla", label: "America/Anguilla (UTC-04:00)", city: "Anguilla", offset: "UTC-04:00", region: "America" },
  { value: "America/Antigua", label: "America/Antigua (UTC-04:00)", city: "Antigua", offset: "UTC-04:00", region: "America" },
  { value: "America/Araguaina", label: "America/Araguaina (UTC-03:00)", city: "Araguaina", offset: "UTC-03:00", region: "America" },
  { value: "America/Argentina/Buenos_Aires", label: "America/Argentina/Buenos_Aires (UTC-03:00)", city: "Buenos Aires", offset: "UTC-03:00", region: "America" },
  { value: "America/Argentina/Catamarca", label: "America/Argentina/Catamarca (UTC-03:00)", city: "Catamarca", offset: "UTC-03:00", region: "America" },
  { value: "America/Argentina/Cordoba", label: "America/Argentina/Cordoba (UTC-03:00)", city: "Cordoba", offset: "UTC-03:00", region: "America" },
  { value: "America/Argentina/Jujuy", label: "America/Argentina/Jujuy (UTC-03:00)", city: "Jujuy", offset: "UTC-03:00", region: "America" },
  { value: "America/Argentina/La_Rioja", label: "America/Argentina/La_Rioja (UTC-03:00)", city: "La Rioja", offset: "UTC-03:00", region: "America" },
  { value: "America/Argentina/Mendoza", label: "America/Argentina/Mendoza (UTC-03:00)", city: "Mendoza", offset: "UTC-03:00", region: "America" },
  { value: "America/Argentina/Rio_Gallegos", label: "America/Argentina/Rio_Gallegos (UTC-03:00)", city: "Rio Gallegos", offset: "UTC-03:00", region: "America" },
  { value: "America/Argentina/Salta", label: "America/Argentina/Salta (UTC-03:00)", city: "Salta", offset: "UTC-03:00", region: "America" },
  { value: "America/Argentina/San_Juan", label: "America/Argentina/San_Juan (UTC-03:00)", city: "San Juan", offset: "UTC-03:00", region: "America" },
  { value: "America/Argentina/San_Luis", label: "America/Argentina/San_Luis (UTC-03:00)", city: "San Luis", offset: "UTC-03:00", region: "America" },
  { value: "America/Argentina/Tucuman", label: "America/Argentina/Tucuman (UTC-03:00)", city: "Tucuman", offset: "UTC-03:00", region: "America" },
  { value: "America/Argentina/Ushuaia", label: "America/Argentina/Ushuaia (UTC-03:00)", city: "Ushuaia", offset: "UTC-03:00", region: "America" },
  { value: "America/Aruba", label: "America/Aruba (UTC-04:00)", city: "Aruba", offset: "UTC-04:00", region: "America" },
  { value: "America/Asuncion", label: "America/Asuncion (UTC-03:00)", city: "Asuncion", offset: "UTC-03:00", region: "America" },
  { value: "America/Atikokan", label: "America/Atikokan (UTC-05:00)", city: "Atikokan", offset: "UTC-05:00", region: "America" },
  { value: "America/Bahia", label: "America/Bahia (UTC-03:00)", city: "Bahia", offset: "UTC-03:00", region: "America" },
  { value: "America/Bahia_Banderas", label: "America/Bahia_Banderas (UTC-06:00)", city: "Bahia Banderas", offset: "UTC-06:00", region: "America" },
  { value: "America/Barbados", label: "America/Barbados (UTC-04:00)", city: "Barbados", offset: "UTC-04:00", region: "America" },
  { value: "America/Belem", label: "America/Belem (UTC-03:00)", city: "Belem", offset: "UTC-03:00", region: "America" },
  { value: "America/Belize", label: "America/Belize (UTC-06:00)", city: "Belize", offset: "UTC-06:00", region: "America" },
  { value: "America/Blanc-Sablon", label: "America/Blanc-Sablon (UTC-04:00)", city: "Blanc-Sablon", offset: "UTC-04:00", region: "America" },
  { value: "America/Boa_Vista", label: "America/Boa_Vista (UTC-04:00)", city: "Boa Vista", offset: "UTC-04:00", region: "America" },
  { value: "America/Bogota", label: "America/Bogota (UTC-05:00)", city: "Bogota", offset: "UTC-05:00", region: "America" },
  { value: "America/Boise", label: "America/Boise (UTC-07:00)", city: "Boise", offset: "UTC-07:00", region: "America" },
  { value: "America/Cambridge_Bay", label: "America/Cambridge_Bay (UTC-07:00)", city: "Cambridge Bay", offset: "UTC-07:00", region: "America" },
  { value: "America/Campo_Grande", label: "America/Campo_Grande (UTC-04:00)", city: "Campo Grande", offset: "UTC-04:00", region: "America" },
  { value: "America/Cancun", label: "America/Cancun (UTC-05:00)", city: "Cancun", offset: "UTC-05:00", region: "America" },
  { value: "America/Caracas", label: "America/Caracas (UTC-04:00)", city: "Caracas", offset: "UTC-04:00", region: "America" },
  { value: "America/Cayenne", label: "America/Cayenne (UTC-03:00)", city: "Cayenne", offset: "UTC-03:00", region: "America" },
  { value: "America/Cayman", label: "America/Cayman (UTC-05:00)", city: "Cayman", offset: "UTC-05:00", region: "America" },
  { value: "America/Chicago", label: "America/Chicago (UTC-06:00)", city: "Chicago", offset: "UTC-06:00", region: "America" },
  { value: "America/Chihuahua", label: "America/Chihuahua (UTC-07:00)", city: "Chihuahua", offset: "UTC-07:00", region: "America" },
  { value: "America/Costa_Rica", label: "America/Costa_Rica (UTC-06:00)", city: "Costa Rica", offset: "UTC-06:00", region: "America" },
  { value: "America/Creston", label: "America/Creston (UTC-07:00)", city: "Creston", offset: "UTC-07:00", region: "America" },
  { value: "America/Cuiaba", label: "America/Cuiaba (UTC-04:00)", city: "Cuiaba", offset: "UTC-04:00", region: "America" },
  { value: "America/Curacao", label: "America/Curacao (UTC-04:00)", city: "Curacao", offset: "UTC-04:00", region: "America" },
  { value: "America/Danmarkshavn", label: "America/Danmarkshavn (UTC+00:00)", city: "Danmarkshavn", offset: "UTC+00:00", region: "America" },
  { value: "America/Dawson", label: "America/Dawson (UTC-07:00)", city: "Dawson", offset: "UTC-07:00", region: "America" },
  { value: "America/Dawson_Creek", label: "America/Dawson_Creek (UTC-07:00)", city: "Dawson Creek", offset: "UTC-07:00", region: "America" },
  { value: "America/Denver", label: "America/Denver (UTC-07:00)", city: "Denver", offset: "UTC-07:00", region: "America" },
  { value: "America/Detroit", label: "America/Detroit (UTC-05:00)", city: "Detroit", offset: "UTC-05:00", region: "America" },
  { value: "America/Dominica", label: "America/Dominica (UTC-04:00)", city: "Dominica", offset: "UTC-04:00", region: "America" },
  { value: "America/Edmonton", label: "America/Edmonton (UTC-07:00)", city: "Edmonton", offset: "UTC-07:00", region: "America" },
  { value: "America/Eirunepe", label: "America/Eirunepe (UTC-05:00)", city: "Eirunepe", offset: "UTC-05:00", region: "America" },
  { value: "America/El_Salvador", label: "America/El_Salvador (UTC-06:00)", city: "El Salvador", offset: "UTC-06:00", region: "America" },
  { value: "America/Fortaleza", label: "America/Fortaleza (UTC-03:00)", city: "Fortaleza", offset: "UTC-03:00", region: "America" },
  { value: "America/Fort_Nelson", label: "America/Fort_Nelson (UTC-07:00)", city: "Fort Nelson", offset: "UTC-07:00", region: "America" },
  { value: "America/Glace_Bay", label: "America/Glace_Bay (UTC-04:00)", city: "Glace Bay", offset: "UTC-04:00", region: "America" },
  { value: "America/Godthab", label: "America/Godthab (UTC-03:00)", city: "Godthab", offset: "UTC-03:00", region: "America" },
  { value: "America/Goose_Bay", label: "America/Goose_Bay (UTC-04:00)", city: "Goose Bay", offset: "UTC-04:00", region: "America" },
  { value: "America/Grand_Turk", label: "America/Grand_Turk (UTC-05:00)", city: "Grand Turk", offset: "UTC-05:00", region: "America" },
  { value: "America/Grenada", label: "America/Grenada (UTC-04:00)", city: "Grenada", offset: "UTC-04:00", region: "America" },
  { value: "America/Guadeloupe", label: "America/Guadeloupe (UTC-04:00)", city: "Guadeloupe", offset: "UTC-04:00", region: "America" },
  { value: "America/Guatemala", label: "America/Guatemala (UTC-06:00)", city: "Guatemala", offset: "UTC-06:00", region: "America" },
  { value: "America/Guayaquil", label: "America/Guayaquil (UTC-05:00)", city: "Guayaquil", offset: "UTC-05:00", region: "America" },
  { value: "America/Guyana", label: "America/Guyana (UTC-04:00)", city: "Guyana", offset: "UTC-04:00", region: "America" },
  { value: "America/Halifax", label: "America/Halifax (UTC-04:00)", city: "Halifax", offset: "UTC-04:00", region: "America" },
  { value: "America/Havana", label: "America/Havana (UTC-05:00)", city: "Havana", offset: "UTC-05:00", region: "America" },
  { value: "America/Hermosillo", label: "America/Hermosillo (UTC-07:00)", city: "Hermosillo", offset: "UTC-07:00", region: "America" },
  { value: "America/Indiana/Indianapolis", label: "America/Indiana/Indianapolis (UTC-05:00)", city: "Indianapolis", offset: "UTC-05:00", region: "America" },
  { value: "America/Indiana/Knox", label: "America/Indiana/Knox (UTC-06:00)", city: "Knox", offset: "UTC-06:00", region: "America" },
  { value: "America/Indiana/Marengo", label: "America/Indiana/Marengo (UTC-05:00)", city: "Marengo", offset: "UTC-05:00", region: "America" },
  { value: "America/Indiana/Petersburg", label: "America/Indiana/Petersburg (UTC-05:00)", city: "Petersburg", offset: "UTC-05:00", region: "America" },
  { value: "America/Indiana/Tell_City", label: "America/Indiana/Tell_City (UTC-06:00)", city: "Tell City", offset: "UTC-06:00", region: "America" },
  { value: "America/Indiana/Vevay", label: "America/Indiana/Vevay (UTC-05:00)", city: "Vevay", offset: "UTC-05:00", region: "America" },
  { value: "America/Indiana/Vincennes", label: "America/Indiana/Vincennes (UTC-05:00)", city: "Vincennes", offset: "UTC-05:00", region: "America" },
  { value: "America/Indiana/Winamac", label: "America/Indiana/Winamac (UTC-05:00)", city: "Winamac", offset: "UTC-05:00", region: "America" },
  { value: "America/Inuvik", label: "America/Inuvik (UTC-07:00)", city: "Inuvik", offset: "UTC-07:00", region: "America" },
  { value: "America/Iqaluit", label: "America/Iqaluit (UTC-05:00)", city: "Iqaluit", offset: "UTC-05:00", region: "America" },
  { value: "America/Jamaica", label: "America/Jamaica (UTC-05:00)", city: "Jamaica", offset: "UTC-05:00", region: "America" },
  { value: "America/Juneau", label: "America/Juneau (UTC-09:00)", city: "Juneau", offset: "UTC-09:00", region: "America" },
  { value: "America/Kentucky/Louisville", label: "America/Kentucky/Louisville (UTC-05:00)", city: "Louisville", offset: "UTC-05:00", region: "America" },
  { value: "America/Kentucky/Monticello", label: "America/Kentucky/Monticello (UTC-05:00)", city: "Monticello", offset: "UTC-05:00", region: "America" },
  { value: "America/Kralendijk", label: "America/Kralendijk (UTC-04:00)", city: "Kralendijk", offset: "UTC-04:00", region: "America" },
  { value: "America/La_Paz", label: "America/La_Paz (UTC-04:00)", city: "La Paz", offset: "UTC-04:00", region: "America" },
  { value: "America/Lima", label: "America/Lima (UTC-05:00)", city: "Lima", offset: "UTC-05:00", region: "America" },
  { value: "America/Los_Angeles", label: "America/Los_Angeles (UTC-08:00)", city: "Los Angeles", offset: "UTC-08:00", region: "America" },
  { value: "America/Lower_Princes", label: "America/Lower_Princes (UTC-04:00)", city: "Lower Princes", offset: "UTC-04:00", region: "America" },
  { value: "America/Maceio", label: "America/Maceio (UTC-03:00)", city: "Maceio", offset: "UTC-03:00", region: "America" },
  { value: "America/Managua", label: "America/Managua (UTC-06:00)", city: "Managua", offset: "UTC-06:00", region: "America" },
  { value: "America/Manaus", label: "America/Manaus (UTC-04:00)", city: "Manaus", offset: "UTC-04:00", region: "America" },
  { value: "America/Marigot", label: "America/Marigot (UTC-04:00)", city: "Marigot", offset: "UTC-04:00", region: "America" },
  { value: "America/Martinique", label: "America/Martinique (UTC-04:00)", city: "Martinique", offset: "UTC-04:00", region: "America" },
  { value: "America/Matamoros", label: "America/Matamoros (UTC-06:00)", city: "Matamoros", offset: "UTC-06:00", region: "America" },
  { value: "America/Mazatlan", label: "America/Mazatlan (UTC-07:00)", city: "Mazatlan", offset: "UTC-07:00", region: "America" },
  { value: "America/Menominee", label: "America/Menominee (UTC-06:00)", city: "Menominee", offset: "UTC-06:00", region: "America" },
  { value: "America/Merida", label: "America/Merida (UTC-06:00)", city: "Merida", offset: "UTC-06:00", region: "America" },
  { value: "America/Metlakatla", label: "America/Metlakatla (UTC-09:00)", city: "Metlakatla", offset: "UTC-09:00", region: "America" },
  { value: "America/Mexico_City", label: "America/Mexico_City (UTC-06:00)", city: "Mexico City", offset: "UTC-06:00", region: "America" },
  { value: "America/Miquelon", label: "America/Miquelon (UTC-03:00)", city: "Miquelon", offset: "UTC-03:00", region: "America" },
  { value: "America/Moncton", label: "America/Moncton (UTC-04:00)", city: "Moncton", offset: "UTC-04:00", region: "America" },
  { value: "America/Monterrey", label: "America/Monterrey (UTC-06:00)", city: "Monterrey", offset: "UTC-06:00", region: "America" },
  { value: "America/Montevideo", label: "America/Montevideo (UTC-03:00)", city: "Montevideo", offset: "UTC-03:00", region: "America" },
  { value: "America/Montserrat", label: "America/Montserrat (UTC-04:00)", city: "Montserrat", offset: "UTC-04:00", region: "America" },
  { value: "America/Nassau", label: "America/Nassau (UTC-05:00)", city: "Nassau", offset: "UTC-05:00", region: "America" },
  { value: "America/New_York", label: "America/New_York (UTC-05:00)", city: "New York", offset: "UTC-05:00", region: "America" },
  { value: "America/Nipigon", label: "America/Nipigon (UTC-05:00)", city: "Nipigon", offset: "UTC-05:00", region: "America" },
  { value: "America/Nome", label: "America/Nome (UTC-09:00)", city: "Nome", offset: "UTC-09:00", region: "America" },
  { value: "America/Noronha", label: "America/Noronha (UTC-02:00)", city: "Noronha", offset: "UTC-02:00", region: "America" },
  { value: "America/North_Dakota/Beulah", label: "America/North_Dakota/Beulah (UTC-06:00)", city: "Beulah", offset: "UTC-06:00", region: "America" },
  { value: "America/North_Dakota/Center", label: "America/North_Dakota/Center (UTC-06:00)", city: "Center", offset: "UTC-06:00", region: "America" },
  { value: "America/North_Dakota/New_Salem", label: "America/North_Dakota/New_Salem (UTC-06:00)", city: "New Salem", offset: "UTC-06:00", region: "America" },
  { value: "America/Ojinaga", label: "America/Ojinaga (UTC-07:00)", city: "Ojinaga", offset: "UTC-07:00", region: "America" },
  { value: "America/Panama", label: "America/Panama (UTC-05:00)", city: "Panama", offset: "UTC-05:00", region: "America" },
  { value: "America/Pangnirtung", label: "America/Pangnirtung (UTC-05:00)", city: "Pangnirtung", offset: "UTC-05:00", region: "America" },
  { value: "America/Paramaribo", label: "America/Paramaribo (UTC-03:00)", city: "Paramaribo", offset: "UTC-03:00", region: "America" },
  { value: "America/Phoenix", label: "America/Phoenix (UTC-07:00)", city: "Phoenix", offset: "UTC-07:00", region: "America" },
  { value: "America/Port-au-Prince", label: "America/Port-au-Prince (UTC-05:00)", city: "Port-au-Prince", offset: "UTC-05:00", region: "America" },
  { value: "America/Port_of_Spain", label: "America/Port_of_Spain (UTC-04:00)", city: "Port of Spain", offset: "UTC-04:00", region: "America" },
  { value: "America/Porto_Velho", label: "America/Porto_Velho (UTC-04:00)", city: "Porto Velho", offset: "UTC-04:00", region: "America" },
  { value: "America/Puerto_Rico", label: "America/Puerto_Rico (UTC-04:00)", city: "Puerto Rico", offset: "UTC-04:00", region: "America" },
  { value: "America/Punta_Arenas", label: "America/Punta_Arenas (UTC-03:00)", city: "Punta Arenas", offset: "UTC-03:00", region: "America" },
  { value: "America/Rainy_River", label: "America/Rainy_River (UTC-06:00)", city: "Rainy River", offset: "UTC-06:00", region: "America" },
  { value: "America/Rankin_Inlet", label: "America/Rankin_Inlet (UTC-06:00)", city: "Rankin Inlet", offset: "UTC-06:00", region: "America" },
  { value: "America/Recife", label: "America/Recife (UTC-03:00)", city: "Recife", offset: "UTC-03:00", region: "America" },
  { value: "America/Regina", label: "America/Regina (UTC-06:00)", city: "Regina", offset: "UTC-06:00", region: "America" },
  { value: "America/Resolute", label: "America/Resolute (UTC-06:00)", city: "Resolute", offset: "UTC-06:00", region: "America" },
  { value: "America/Rio_Branco", label: "America/Rio_Branco (UTC-05:00)", city: "Rio Branco", offset: "UTC-05:00", region: "America" },
  { value: "America/Santarem", label: "America/Santarem (UTC-03:00)", city: "Santarem", offset: "UTC-03:00", region: "America" },
  { value: "America/Santiago", label: "America/Santiago (UTC-04:00)", city: "Santiago", offset: "UTC-04:00", region: "America" },
  { value: "America/Santo_Domingo", label: "America/Santo_Domingo (UTC-04:00)", city: "Santo Domingo", offset: "UTC-04:00", region: "America" },
  { value: "America/Sao_Paulo", label: "America/Sao_Paulo (UTC-03:00)", city: "Sao Paulo", offset: "UTC-03:00", region: "America" },
  { value: "America/Scoresbysund", label: "America/Scoresbysund (UTC-01:00)", city: "Scoresbysund", offset: "UTC-01:00", region: "America" },
  { value: "America/Sitka", label: "America/Sitka (UTC-09:00)", city: "Sitka", offset: "UTC-09:00", region: "America" },
  { value: "America/St_Barthelemy", label: "America/St_Barthelemy (UTC-04:00)", city: "St Barthelemy", offset: "UTC-04:00", region: "America" },
  { value: "America/St_Johns", label: "America/St_Johns (UTC-03:30)", city: "St Johns", offset: "UTC-03:30", region: "America" },
  { value: "America/St_Kitts", label: "America/St_Kitts (UTC-04:00)", city: "St Kitts", offset: "UTC-04:00", region: "America" },
  { value: "America/St_Lucia", label: "America/St_Lucia (UTC-04:00)", city: "St Lucia", offset: "UTC-04:00", region: "America" },
  { value: "America/St_Thomas", label: "America/St_Thomas (UTC-04:00)", city: "St Thomas", offset: "UTC-04:00", region: "America" },
  { value: "America/St_Vincent", label: "America/St_Vincent (UTC-04:00)", city: "St Vincent", offset: "UTC-04:00", region: "America" },
  { value: "America/Swift_Current", label: "America/Swift_Current (UTC-06:00)", city: "Swift Current", offset: "UTC-06:00", region: "America" },
  { value: "America/Tegucigalpa", label: "America/Tegucigalpa (UTC-06:00)", city: "Tegucigalpa", offset: "UTC-06:00", region: "America" },
  { value: "America/Thule", label: "America/Thule (UTC-04:00)", city: "Thule", offset: "UTC-04:00", region: "America" },
  { value: "America/Thunder_Bay", label: "America/Thunder_Bay (UTC-05:00)", city: "Thunder Bay", offset: "UTC-05:00", region: "America" },
  { value: "America/Tijuana", label: "America/Tijuana (UTC-08:00)", city: "Tijuana", offset: "UTC-08:00", region: "America" },
  { value: "America/Toronto", label: "America/Toronto (UTC-05:00)", city: "Toronto", offset: "UTC-05:00", region: "America" },
  { value: "America/Tortola", label: "America/Tortola (UTC-04:00)", city: "Tortola", offset: "UTC-04:00", region: "America" },
  { value: "America/Vancouver", label: "America/Vancouver (UTC-08:00)", city: "Vancouver", offset: "UTC-08:00", region: "America" },
  { value: "America/Whitehorse", label: "America/Whitehorse (UTC-07:00)", city: "Whitehorse", offset: "UTC-07:00", region: "America" },
  { value: "America/Winnipeg", label: "America/Winnipeg (UTC-06:00)", city: "Winnipeg", offset: "UTC-06:00", region: "America" },
  { value: "America/Yakutat", label: "America/Yakutat (UTC-09:00)", city: "Yakutat", offset: "UTC-09:00", region: "America" },
  { value: "America/Yellowknife", label: "America/Yellowknife (UTC-07:00)", city: "Yellowknife", offset: "UTC-07:00", region: "America" },

  // Asia
  { value: "Asia/Aden", label: "Asia/Aden (UTC+03:00)", city: "Aden", offset: "UTC+03:00", region: "Asia" },
  { value: "Asia/Almaty", label: "Asia/Almaty (UTC+06:00)", city: "Almaty", offset: "UTC+06:00", region: "Asia" },
  { value: "Asia/Amman", label: "Asia/Amman (UTC+03:00)", city: "Amman", offset: "UTC+03:00", region: "Asia" },
  { value: "Asia/Anadyr", label: "Asia/Anadyr (UTC+12:00)", city: "Anadyr", offset: "UTC+12:00", region: "Asia" },
  { value: "Asia/Aqtau", label: "Asia/Aqtau (UTC+05:00)", city: "Aqtau", offset: "UTC+05:00", region: "Asia" },
  { value: "Asia/Aqtobe", label: "Asia/Aqtobe (UTC+05:00)", city: "Aqtobe", offset: "UTC+05:00", region: "Asia" },
  { value: "Asia/Ashgabat", label: "Asia/Ashgabat (UTC+05:00)", city: "Ashgabat", offset: "UTC+05:00", region: "Asia" },
  { value: "Asia/Atyrau", label: "Asia/Atyrau (UTC+05:00)", city: "Atyrau", offset: "UTC+05:00", region: "Asia" },
  { value: "Asia/Baghdad", label: "Asia/Baghdad (UTC+03:00)", city: "Baghdad", offset: "UTC+03:00", region: "Asia" },
  { value: "Asia/Bahrain", label: "Asia/Bahrain (UTC+03:00)", city: "Bahrain", offset: "UTC+03:00", region: "Asia" },
  { value: "Asia/Baku", label: "Asia/Baku (UTC+04:00)", city: "Baku", offset: "UTC+04:00", region: "Asia" },
  { value: "Asia/Bangkok", label: "Asia/Bangkok (UTC+07:00)", city: "Bangkok", offset: "UTC+07:00", region: "Asia" },
  { value: "Asia/Barnaul", label: "Asia/Barnaul (UTC+07:00)", city: "Barnaul", offset: "UTC+07:00", region: "Asia" },
  { value: "Asia/Beirut", label: "Asia/Beirut (UTC+02:00)", city: "Beirut", offset: "UTC+02:00", region: "Asia" },
  { value: "Asia/Bishkek", label: "Asia/Bishkek (UTC+06:00)", city: "Bishkek", offset: "UTC+06:00", region: "Asia" },
  { value: "Asia/Brunei", label: "Asia/Brunei (UTC+08:00)", city: "Brunei", offset: "UTC+08:00", region: "Asia" },
  { value: "Asia/Chita", label: "Asia/Chita (UTC+09:00)", city: "Chita", offset: "UTC+09:00", region: "Asia" },
  { value: "Asia/Choibalsan", label: "Asia/Choibalsan (UTC+08:00)", city: "Choibalsan", offset: "UTC+08:00", region: "Asia" },
  { value: "Asia/Colombo", label: "Asia/Colombo (UTC+05:30)", city: "Colombo", offset: "UTC+05:30", region: "Asia" },
  { value: "Asia/Damascus", label: "Asia/Damascus (UTC+03:00)", city: "Damascus", offset: "UTC+03:00", region: "Asia" },
  { value: "Asia/Dhaka", label: "Asia/Dhaka (UTC+06:00)", city: "Dhaka", offset: "UTC+06:00", region: "Asia" },
  { value: "Asia/Dili", label: "Asia/Dili (UTC+09:00)", city: "Dili", offset: "UTC+09:00", region: "Asia" },
  { value: "Asia/Dubai", label: "Asia/Dubai (UTC+04:00)", city: "Dubai", offset: "UTC+04:00", region: "Asia" },
  { value: "Asia/Dushanbe", label: "Asia/Dushanbe (UTC+05:00)", city: "Dushanbe", offset: "UTC+05:00", region: "Asia" },
  { value: "Asia/Famagusta", label: "Asia/Famagusta (UTC+02:00)", city: "Famagusta", offset: "UTC+02:00", region: "Asia" },
  { value: "Asia/Gaza", label: "Asia/Gaza (UTC+02:00)", city: "Gaza", offset: "UTC+02:00", region: "Asia" },
  { value: "Asia/Hebron", label: "Asia/Hebron (UTC+02:00)", city: "Hebron", offset: "UTC+02:00", region: "Asia" },
  { value: "Asia/Ho_Chi_Minh", label: "Asia/Ho_Chi_Minh (UTC+07:00)", city: "Ho Chi Minh", offset: "UTC+07:00", region: "Asia" },
  { value: "Asia/Hong_Kong", label: "Asia/Hong_Kong (UTC+08:00)", city: "Hong Kong", offset: "UTC+08:00", region: "Asia" },
  { value: "Asia/Hovd", label: "Asia/Hovd (UTC+07:00)", city: "Hovd", offset: "UTC+07:00", region: "Asia" },
  { value: "Asia/Irkutsk", label: "Asia/Irkutsk (UTC+08:00)", city: "Irkutsk", offset: "UTC+08:00", region: "Asia" },
  { value: "Asia/Jakarta", label: "Asia/Jakarta (UTC+07:00)", city: "Jakarta", offset: "UTC+07:00", region: "Asia" },
  { value: "Asia/Jayapura", label: "Asia/Jayapura (UTC+09:00)", city: "Jayapura", offset: "UTC+09:00", region: "Asia" },
  { value: "Asia/Jerusalem", label: "Asia/Jerusalem (UTC+02:00)", city: "Jerusalem", offset: "UTC+02:00", region: "Asia" },
  { value: "Asia/Kabul", label: "Asia/Kabul (UTC+04:30)", city: "Kabul", offset: "UTC+04:30", region: "Asia" },
  { value: "Asia/Kamchatka", label: "Asia/Kamchatka (UTC+12:00)", city: "Kamchatka", offset: "UTC+12:00", region: "Asia" },
  { value: "Asia/Karachi", label: "Asia/Karachi (UTC+05:00)", city: "Karachi", offset: "UTC+05:00", region: "Asia" },
  { value: "Asia/Kathmandu", label: "Asia/Kathmandu (UTC+05:45)", city: "Kathmandu", offset: "UTC+05:45", region: "Asia" },
  { value: "Asia/Khandyga", label: "Asia/Khandyga (UTC+09:00)", city: "Khandyga", offset: "UTC+09:00", region: "Asia" },
  { value: "Asia/Kolkata", label: "Asia/Kolkata (UTC+05:30)", city: "Kolkata", offset: "UTC+05:30", region: "Asia" },
  { value: "Asia/Krasnoyarsk", label: "Asia/Krasnoyarsk (UTC+07:00)", city: "Krasnoyarsk", offset: "UTC+07:00", region: "Asia" },
  { value: "Asia/Kuala_Lumpur", label: "Asia/Kuala_Lumpur (UTC+08:00)", city: "Kuala Lumpur", offset: "UTC+08:00", region: "Asia" },
  { value: "Asia/Kuching", label: "Asia/Kuching (UTC+08:00)", city: "Kuching", offset: "UTC+08:00", region: "Asia" },
  { value: "Asia/Kuwait", label: "Asia/Kuwait (UTC+03:00)", city: "Kuwait", offset: "UTC+03:00", region: "Asia" },
  { value: "Asia/Macau", label: "Asia/Macau (UTC+08:00)", city: "Macau", offset: "UTC+08:00", region: "Asia" },
  { value: "Asia/Magadan", label: "Asia/Magadan (UTC+11:00)", city: "Magadan", offset: "UTC+11:00", region: "Asia" },
  { value: "Asia/Makassar", label: "Asia/Makassar (UTC+08:00)", city: "Makassar", offset: "UTC+08:00", region: "Asia" },
  { value: "Asia/Manila", label: "Asia/Manila (UTC+08:00)", city: "Manila", offset: "UTC+08:00", region: "Asia" },
  { value: "Asia/Muscat", label: "Asia/Muscat (UTC+04:00)", city: "Muscat", offset: "UTC+04:00", region: "Asia" },
  { value: "Asia/Nicosia", label: "Asia/Nicosia (UTC+02:00)", city: "Nicosia", offset: "UTC+02:00", region: "Asia" },
  { value: "Asia/Novokuznetsk", label: "Asia/Novokuznetsk (UTC+07:00)", city: "Novokuznetsk", offset: "UTC+07:00", region: "Asia" },
  { value: "Asia/Novosibirsk", label: "Asia/Novosibirsk (UTC+07:00)", city: "Novosibirsk", offset: "UTC+07:00", region: "Asia" },
  { value: "Asia/Omsk", label: "Asia/Omsk (UTC+06:00)", city: "Omsk", offset: "UTC+06:00", region: "Asia" },
  { value: "Asia/Oral", label: "Asia/Oral (UTC+05:00)", city: "Oral", offset: "UTC+05:00", region: "Asia" },
  { value: "Asia/Phnom_Penh", label: "Asia/Phnom_Penh (UTC+07:00)", city: "Phnom Penh", offset: "UTC+07:00", region: "Asia" },
  { value: "Asia/Pontianak", label: "Asia/Pontianak (UTC+07:00)", city: "Pontianak", offset: "UTC+07:00", region: "Asia" },
  { value: "Asia/Pyongyang", label: "Asia/Pyongyang (UTC+09:00)", city: "Pyongyang", offset: "UTC+09:00", region: "Asia" },
  { value: "Asia/Qatar", label: "Asia/Qatar (UTC+03:00)", city: "Qatar", offset: "UTC+03:00", region: "Asia" },
  { value: "Asia/Qostanay", label: "Asia/Qostanay (UTC+06:00)", city: "Qostanay", offset: "UTC+06:00", region: "Asia" },
  { value: "Asia/Qyzylorda", label: "Asia/Qyzylorda (UTC+05:00)", city: "Qyzylorda", offset: "UTC+05:00", region: "Asia" },
  { value: "Asia/Riyadh", label: "Asia/Riyadh (UTC+03:00)", city: "Riyadh", offset: "UTC+03:00", region: "Asia" },
  { value: "Asia/Sakhalin", label: "Asia/Sakhalin (UTC+11:00)", city: "Sakhalin", offset: "UTC+11:00", region: "Asia" },
  { value: "Asia/Samarkand", label: "Asia/Samarkand (UTC+05:00)", city: "Samarkand", offset: "UTC+05:00", region: "Asia" },
  { value: "Asia/Seoul", label: "Asia/Seoul (UTC+09:00)", city: "Seoul", offset: "UTC+09:00", region: "Asia" },
  { value: "Asia/Shanghai", label: "Asia/Shanghai (UTC+08:00)", city: "Shanghai", offset: "UTC+08:00", region: "Asia" },
  { value: "Asia/Singapore", label: "Asia/Singapore (UTC+08:00)", city: "Singapore", offset: "UTC+08:00", region: "Asia" },
  { value: "Asia/Srednekolymsk", label: "Asia/Srednekolymsk (UTC+11:00)", city: "Srednekolymsk", offset: "UTC+11:00", region: "Asia" },
  { value: "Asia/Taipei", label: "Asia/Taipei (UTC+08:00)", city: "Taipei", offset: "UTC+08:00", region: "Asia" },
  { value: "Asia/Tashkent", label: "Asia/Tashkent (UTC+05:00)", city: "Tashkent", offset: "UTC+05:00", region: "Asia" },
  { value: "Asia/Tbilisi", label: "Asia/Tbilisi (UTC+04:00)", city: "Tbilisi", offset: "UTC+04:00", region: "Asia" },
  { value: "Asia/Tehran", label: "Asia/Tehran (UTC+03:30)", city: "Tehran", offset: "UTC+03:30", region: "Asia" },
  { value: "Asia/Thimphu", label: "Asia/Thimphu (UTC+06:00)", city: "Thimphu", offset: "UTC+06:00", region: "Asia" },
  { value: "Asia/Tokyo", label: "Asia/Tokyo (UTC+09:00)", city: "Tokyo", offset: "UTC+09:00", region: "Asia" },
  { value: "Asia/Tomsk", label: "Asia/Tomsk (UTC+07:00)", city: "Tomsk", offset: "UTC+07:00", region: "Asia" },
  { value: "Asia/Ulaanbaatar", label: "Asia/Ulaanbaatar (UTC+08:00)", city: "Ulaanbaatar", offset: "UTC+08:00", region: "Asia" },
  { value: "Asia/Urumqi", label: "Asia/Urumqi (UTC+06:00)", city: "Urumqi", offset: "UTC+06:00", region: "Asia" },
  { value: "Asia/Ust-Nera", label: "Asia/Ust-Nera (UTC+10:00)", city: "Ust-Nera", offset: "UTC+10:00", region: "Asia" },
  { value: "Asia/Vientiane", label: "Asia/Vientiane (UTC+07:00)", city: "Vientiane", offset: "UTC+07:00", region: "Asia" },
  { value: "Asia/Vladivostok", label: "Asia/Vladivostok (UTC+10:00)", city: "Vladivostok", offset: "UTC+10:00", region: "Asia" },
  { value: "Asia/Yakutsk", label: "Asia/Yakutsk (UTC+09:00)", city: "Yakutsk", offset: "UTC+09:00", region: "Asia" },
  { value: "Asia/Yangon", label: "Asia/Yangon (UTC+06:30)", city: "Yangon", offset: "UTC+06:30", region: "Asia" },
  { value: "Asia/Yekaterinburg", label: "Asia/Yekaterinburg (UTC+05:00)", city: "Yekaterinburg", offset: "UTC+05:00", region: "Asia" },
  { value: "Asia/Yerevan", label: "Asia/Yerevan (UTC+04:00)", city: "Yerevan", offset: "UTC+04:00", region: "Asia" },

  // Atlantic
  { value: "Atlantic/Azores", label: "Atlantic/Azores (UTC-01:00)", city: "Azores", offset: "UTC-01:00", region: "Atlantic" },
  { value: "Atlantic/Bermuda", label: "Atlantic/Bermuda (UTC-04:00)", city: "Bermuda", offset: "UTC-04:00", region: "Atlantic" },
  { value: "Atlantic/Canary", label: "Atlantic/Canary (UTC+00:00)", city: "Canary", offset: "UTC+00:00", region: "Atlantic" },
  { value: "Atlantic/Cape_Verde", label: "Atlantic/Cape_Verde (UTC-01:00)", city: "Cape Verde", offset: "UTC-01:00", region: "Atlantic" },
  { value: "Atlantic/Faroe", label: "Atlantic/Faroe (UTC+00:00)", city: "Faroe", offset: "UTC+00:00", region: "Atlantic" },
  { value: "Atlantic/Madeira", label: "Atlantic/Madeira (UTC+00:00)", city: "Madeira", offset: "UTC+00:00", region: "Atlantic" },
  { value: "Atlantic/Reykjavik", label: "Atlantic/Reykjavik (UTC+00:00)", city: "Reykjavik", offset: "UTC+00:00", region: "Atlantic" },
  { value: "Atlantic/South_Georgia", label: "Atlantic/South_Georgia (UTC-02:00)", city: "South Georgia", offset: "UTC-02:00", region: "Atlantic" },
  { value: "Atlantic/St_Helena", label: "Atlantic/St_Helena (UTC+00:00)", city: "St Helena", offset: "UTC+00:00", region: "Atlantic" },
  { value: "Atlantic/Stanley", label: "Atlantic/Stanley (UTC-03:00)", city: "Stanley", offset: "UTC-03:00", region: "Atlantic" },

  // Australia
  { value: "Australia/Adelaide", label: "Australia/Adelaide (UTC+09:30)", city: "Adelaide", offset: "UTC+09:30", region: "Australia" },
  { value: "Australia/Brisbane", label: "Australia/Brisbane (UTC+10:00)", city: "Brisbane", offset: "UTC+10:00", region: "Australia" },
  { value: "Australia/Broken_Hill", label: "Australia/Broken_Hill (UTC+09:30)", city: "Broken Hill", offset: "UTC+09:30", region: "Australia" },
  { value: "Australia/Currie", label: "Australia/Currie (UTC+10:00)", city: "Currie", offset: "UTC+10:00", region: "Australia" },
  { value: "Australia/Darwin", label: "Australia/Darwin (UTC+09:30)", city: "Darwin", offset: "UTC+09:30", region: "Australia" },
  { value: "Australia/Eucla", label: "Australia/Eucla (UTC+08:45)", city: "Eucla", offset: "UTC+08:45", region: "Australia" },
  { value: "Australia/Hobart", label: "Australia/Hobart (UTC+10:00)", city: "Hobart", offset: "UTC+10:00", region: "Australia" },
  { value: "Australia/Lindeman", label: "Australia/Lindeman (UTC+10:00)", city: "Lindeman", offset: "UTC+10:00", region: "Australia" },
  { value: "Australia/Lord_Howe", label: "Australia/Lord_Howe (UTC+10:30)", city: "Lord Howe", offset: "UTC+10:30", region: "Australia" },
  { value: "Australia/Melbourne", label: "Australia/Melbourne (UTC+10:00)", city: "Melbourne", offset: "UTC+10:00", region: "Australia" },
  { value: "Australia/Perth", label: "Australia/Perth (UTC+08:00)", city: "Perth", offset: "UTC+08:00", region: "Australia" },
  { value: "Australia/Sydney", label: "Australia/Sydney (UTC+10:00)", city: "Sydney", offset: "UTC+10:00", region: "Australia" },

  // Europe
  { value: "Europe/Amsterdam", label: "Europe/Amsterdam (UTC+01:00)", city: "Amsterdam", offset: "UTC+01:00", region: "Europe" },
  { value: "Europe/Andorra", label: "Europe/Andorra (UTC+01:00)", city: "Andorra", offset: "UTC+01:00", region: "Europe" },
  { value: "Europe/Astrakhan", label: "Europe/Astrakhan (UTC+04:00)", city: "Astrakhan", offset: "UTC+04:00", region: "Europe" },
  { value: "Europe/Athens", label: "Europe/Athens (UTC+02:00)", city: "Athens", offset: "UTC+02:00", region: "Europe" },
  { value: "Europe/Belgrade", label: "Europe/Belgrade (UTC+01:00)", city: "Belgrade", offset: "UTC+01:00", region: "Europe" },
  { value: "Europe/Berlin", label: "Europe/Berlin (UTC+01:00)", city: "Berlin", offset: "UTC+01:00", region: "Europe" },
  { value: "Europe/Bratislava", label: "Europe/Bratislava (UTC+01:00)", city: "Bratislava", offset: "UTC+01:00", region: "Europe" },
  { value: "Europe/Brussels", label: "Europe/Brussels (UTC+01:00)", city: "Brussels", offset: "UTC+01:00", region: "Europe" },
  { value: "Europe/Bucharest", label: "Europe/Bucharest (UTC+02:00)", city: "Bucharest", offset: "UTC+02:00", region: "Europe" },
  { value: "Europe/Budapest", label: "Europe/Budapest (UTC+01:00)", city: "Budapest", offset: "UTC+01:00", region: "Europe" },
  { value: "Europe/Busingen", label: "Europe/Busingen (UTC+01:00)", city: "Busingen", offset: "UTC+01:00", region: "Europe" },
  { value: "Europe/Chisinau", label: "Europe/Chisinau (UTC+02:00)", city: "Chisinau", offset: "UTC+02:00", region: "Europe" },
  { value: "Europe/Copenhagen", label: "Europe/Copenhagen (UTC+01:00)", city: "Copenhagen", offset: "UTC+01:00", region: "Europe" },
  { value: "Europe/Dublin", label: "Europe/Dublin (UTC+00:00)", city: "Dublin", offset: "UTC+00:00", region: "Europe" },
  { value: "Europe/Gibraltar", label: "Europe/Gibraltar (UTC+01:00)", city: "Gibraltar", offset: "UTC+01:00", region: "Europe" },
  { value: "Europe/Guernsey", label: "Europe/Guernsey (UTC+00:00)", city: "Guernsey", offset: "UTC+00:00", region: "Europe" },
  { value: "Europe/Helsinki", label: "Europe/Helsinki (UTC+02:00)", city: "Helsinki", offset: "UTC+02:00", region: "Europe" },
  { value: "Europe/Isle_of_Man", label: "Europe/Isle_of_Man (UTC+00:00)", city: "Isle of Man", offset: "UTC+00:00", region: "Europe" },
  { value: "Europe/Istanbul", label: "Europe/Istanbul (UTC+03:00)", city: "Istanbul", offset: "UTC+03:00", region: "Europe" },
  { value: "Europe/Jersey", label: "Europe/Jersey (UTC+00:00)", city: "Jersey", offset: "UTC+00:00", region: "Europe" },
  { value: "Europe/Kaliningrad", label: "Europe/Kaliningrad (UTC+02:00)", city: "Kaliningrad", offset: "UTC+02:00", region: "Europe" },
  { value: "Europe/Kiev", label: "Europe/Kiev (UTC+02:00)", city: "Kiev", offset: "UTC+02:00", region: "Europe" },
  { value: "Europe/Kirov", label: "Europe/Kirov (UTC+03:00)", city: "Kirov", offset: "UTC+03:00", region: "Europe" },
  { value: "Europe/Lisbon", label: "Europe/Lisbon (UTC+00:00)", city: "Lisbon", offset: "UTC+00:00", region: "Europe" },
  { value: "Europe/Ljubljana", label: "Europe/Ljubljana (UTC+01:00)", city: "Ljubljana", offset: "UTC+01:00", region: "Europe" },
  { value: "Europe/London", label: "Europe/London (UTC+00:00)", city: "London", offset: "UTC+00:00", region: "Europe" },
  { value: "Europe/Luxembourg", label: "Europe/Luxembourg (UTC+01:00)", city: "Luxembourg", offset: "UTC+01:00", region: "Europe" },
  { value: "Europe/Madrid", label: "Europe/Madrid (UTC+01:00)", city: "Madrid", offset: "UTC+01:00", region: "Europe" },
  { value: "Europe/Malta", label: "Europe/Malta (UTC+01:00)", city: "Malta", offset: "UTC+01:00", region: "Europe" },
  { value: "Europe/Mariehamn", label: "Europe/Mariehamn (UTC+02:00)", city: "Mariehamn", offset: "UTC+02:00", region: "Europe" },
  { value: "Europe/Minsk", label: "Europe/Minsk (UTC+03:00)", city: "Minsk", offset: "UTC+03:00", region: "Europe" },
  { value: "Europe/Monaco", label: "Europe/Monaco (UTC+01:00)", city: "Monaco", offset: "UTC+01:00", region: "Europe" },
  { value: "Europe/Moscow", label: "Europe/Moscow (UTC+03:00)", city: "Moscow", offset: "UTC+03:00", region: "Europe" },
  { value: "Europe/Oslo", label: "Europe/Oslo (UTC+01:00)", city: "Oslo", offset: "UTC+01:00", region: "Europe" },
  { value: "Europe/Paris", label: "Europe/Paris (UTC+01:00)", city: "Paris", offset: "UTC+01:00", region: "Europe" },
  { value: "Europe/Podgorica", label: "Europe/Podgorica (UTC+01:00)", city: "Podgorica", offset: "UTC+01:00", region: "Europe" },
  { value: "Europe/Prague", label: "Europe/Prague (UTC+01:00)", city: "Prague", offset: "UTC+01:00", region: "Europe" },
  { value: "Europe/Riga", label: "Europe/Riga (UTC+02:00)", city: "Riga", offset: "UTC+02:00", region: "Europe" },
  { value: "Europe/Rome", label: "Europe/Rome (UTC+01:00)", city: "Rome", offset: "UTC+01:00", region: "Europe" },
  { value: "Europe/Samara", label: "Europe/Samara (UTC+04:00)", city: "Samara", offset: "UTC+04:00", region: "Europe" },
  { value: "Europe/San_Marino", label: "Europe/San_Marino (UTC+01:00)", city: "San Marino", offset: "UTC+01:00", region: "Europe" },
  { value: "Europe/Sarajevo", label: "Europe/Sarajevo (UTC+01:00)", city: "Sarajevo", offset: "UTC+01:00", region: "Europe" },
  { value: "Europe/Saratov", label: "Europe/Saratov (UTC+04:00)", city: "Saratov", offset: "UTC+04:00", region: "Europe" },
  { value: "Europe/Simferopol", label: "Europe/Simferopol (UTC+03:00)", city: "Simferopol", offset: "UTC+03:00", region: "Europe" },
  { value: "Europe/Skopje", label: "Europe/Skopje (UTC+01:00)", city: "Skopje", offset: "UTC+01:00", region: "Europe" },
  { value: "Europe/Sofia", label: "Europe/Sofia (UTC+02:00)", city: "Sofia", offset: "UTC+02:00", region: "Europe" },
  { value: "Europe/Stockholm", label: "Europe/Stockholm (UTC+01:00)", city: "Stockholm", offset: "UTC+01:00", region: "Europe" },
  { value: "Europe/Tallinn", label: "Europe/Tallinn (UTC+02:00)", city: "Tallinn", offset: "UTC+02:00", region: "Europe" },
  { value: "Europe/Tirane", label: "Europe/Tirane (UTC+01:00)", city: "Tirane", offset: "UTC+01:00", region: "Europe" },
  { value: "Europe/Ulyanovsk", label: "Europe/Ulyanovsk (UTC+04:00)", city: "Ulyanovsk", offset: "UTC+04:00", region: "Europe" },
  { value: "Europe/Uzhgorod", label: "Europe/Uzhgorod (UTC+02:00)", city: "Uzhgorod", offset: "UTC+02:00", region: "Europe" },
  { value: "Europe/Vaduz", label: "Europe/Vaduz (UTC+01:00)", city: "Vaduz", offset: "UTC+01:00", region: "Europe" },
  { value: "Europe/Vatican", label: "Europe/Vatican (UTC+01:00)", city: "Vatican", offset: "UTC+01:00", region: "Europe" },
  { value: "Europe/Vienna", label: "Europe/Vienna (UTC+01:00)", city: "Vienna", offset: "UTC+01:00", region: "Europe" },
  { value: "Europe/Vilnius", label: "Europe/Vilnius (UTC+02:00)", city: "Vilnius", offset: "UTC+02:00", region: "Europe" },
  { value: "Europe/Volgograd", label: "Europe/Volgograd (UTC+03:00)", city: "Volgograd", offset: "UTC+03:00", region: "Europe" },
  { value: "Europe/Warsaw", label: "Europe/Warsaw (UTC+01:00)", city: "Warsaw", offset: "UTC+01:00", region: "Europe" },
  { value: "Europe/Zagreb", label: "Europe/Zagreb (UTC+01:00)", city: "Zagreb", offset: "UTC+01:00", region: "Europe" },
  { value: "Europe/Zaporozhye", label: "Europe/Zaporozhye (UTC+02:00)", city: "Zaporozhye", offset: "UTC+02:00", region: "Europe" },
  { value: "Europe/Zurich", label: "Europe/Zurich (UTC+01:00)", city: "Zurich", offset: "UTC+01:00", region: "Europe" },

  // Indian
  { value: "Indian/Antananarivo", label: "Indian/Antananarivo (UTC+03:00)", city: "Antananarivo", offset: "UTC+03:00", region: "Indian" },
  { value: "Indian/Chagos", label: "Indian/Chagos (UTC+06:00)", city: "Chagos", offset: "UTC+06:00", region: "Indian" },
  { value: "Indian/Christmas", label: "Indian/Christmas (UTC+07:00)", city: "Christmas", offset: "UTC+07:00", region: "Indian" },
  { value: "Indian/Cocos", label: "Indian/Cocos (UTC+06:30)", city: "Cocos", offset: "UTC+06:30", region: "Indian" },
  { value: "Indian/Comoro", label: "Indian/Comoro (UTC+03:00)", city: "Comoro", offset: "UTC+03:00", region: "Indian" },
  { value: "Indian/Kerguelen", label: "Indian/Kerguelen (UTC+05:00)", city: "Kerguelen", offset: "UTC+05:00", region: "Indian" },
  { value: "Indian/Mahe", label: "Indian/Mahe (UTC+04:00)", city: "Mahe", offset: "UTC+04:00", region: "Indian" },
  { value: "Indian/Maldives", label: "Indian/Maldives (UTC+05:00)", city: "Maldives", offset: "UTC+05:00", region: "Indian" },
  { value: "Indian/Mauritius", label: "Indian/Mauritius (UTC+04:00)", city: "Mauritius", offset: "UTC+04:00", region: "Indian" },
  { value: "Indian/Mayotte", label: "Indian/Mayotte (UTC+03:00)", city: "Mayotte", offset: "UTC+03:00", region: "Indian" },
  { value: "Indian/Reunion", label: "Indian/Reunion (UTC+04:00)", city: "Reunion", offset: "UTC+04:00", region: "Indian" },

  // Pacific
  { value: "Pacific/Apia", label: "Pacific/Apia (UTC+13:00)", city: "Apia", offset: "UTC+13:00", region: "Pacific" },
  { value: "Pacific/Auckland", label: "Pacific/Auckland (UTC+12:00)", city: "Auckland", offset: "UTC+12:00", region: "Pacific" },
  { value: "Pacific/Bougainville", label: "Pacific/Bougainville (UTC+11:00)", city: "Bougainville", offset: "UTC+11:00", region: "Pacific" },
  { value: "Pacific/Chatham", label: "Pacific/Chatham (UTC+12:45)", city: "Chatham", offset: "UTC+12:45", region: "Pacific" },
  { value: "Pacific/Chuuk", label: "Pacific/Chuuk (UTC+10:00)", city: "Chuuk", offset: "UTC+10:00", region: "Pacific" },
  { value: "Pacific/Easter", label: "Pacific/Easter (UTC-06:00)", city: "Easter", offset: "UTC-06:00", region: "Pacific" },
  { value: "Pacific/Efate", label: "Pacific/Efate (UTC+11:00)", city: "Efate", offset: "UTC+11:00", region: "Pacific" },
  { value: "Pacific/Enderbury", label: "Pacific/Enderbury (UTC+13:00)", city: "Enderbury", offset: "UTC+13:00", region: "Pacific" },
  { value: "Pacific/Fakaofo", label: "Pacific/Fakaofo (UTC+13:00)", city: "Fakaofo", offset: "UTC+13:00", region: "Pacific" },
  { value: "Pacific/Fiji", label: "Pacific/Fiji (UTC+12:00)", city: "Fiji", offset: "UTC+12:00", region: "Pacific" },
  { value: "Pacific/Funafuti", label: "Pacific/Funafuti (UTC+12:00)", city: "Funafuti", offset: "UTC+12:00", region: "Pacific" },
  { value: "Pacific/Galapagos", label: "Pacific/Galapagos (UTC-06:00)", city: "Galapagos", offset: "UTC-06:00", region: "Pacific" },
  { value: "Pacific/Gambier", label: "Pacific/Gambier (UTC-09:00)", city: "Gambier", offset: "UTC-09:00", region: "Pacific" },
  { value: "Pacific/Guadalcanal", label: "Pacific/Guadalcanal (UTC+11:00)", city: "Guadalcanal", offset: "UTC+11:00", region: "Pacific" },
  { value: "Pacific/Guam", label: "Pacific/Guam (UTC+10:00)", city: "Guam", offset: "UTC+10:00", region: "Pacific" },
  { value: "Pacific/Honolulu", label: "Pacific/Honolulu (UTC-10:00)", city: "Honolulu", offset: "UTC-10:00", region: "Pacific" },
  { value: "Pacific/Kiritimati", label: "Pacific/Kiritimati (UTC+14:00)", city: "Kiritimati", offset: "UTC+14:00", region: "Pacific" },
  { value: "Pacific/Kosrae", label: "Pacific/Kosrae (UTC+11:00)", city: "Kosrae", offset: "UTC+11:00", region: "Pacific" },
  { value: "Pacific/Kwajalein", label: "Pacific/Kwajalein (UTC+12:00)", city: "Kwajalein", offset: "UTC+12:00", region: "Pacific" },
  { value: "Pacific/Majuro", label: "Pacific/Majuro (UTC+12:00)", city: "Majuro", offset: "UTC+12:00", region: "Pacific" },
  { value: "Pacific/Marquesas", label: "Pacific/Marquesas (UTC-09:30)", city: "Marquesas", offset: "UTC-09:30", region: "Pacific" },
  { value: "Pacific/Midway", label: "Pacific/Midway (UTC-11:00)", city: "Midway", offset: "UTC-11:00", region: "Pacific" },
  { value: "Pacific/Nauru", label: "Pacific/Nauru (UTC+12:00)", city: "Nauru", offset: "UTC+12:00", region: "Pacific" },
  { value: "Pacific/Niue", label: "Pacific/Niue (UTC-11:00)", city: "Niue", offset: "UTC-11:00", region: "Pacific" },
  { value: "Pacific/Norfolk", label: "Pacific/Norfolk (UTC+11:00)", city: "Norfolk", offset: "UTC+11:00", region: "Pacific" },
  { value: "Pacific/Noumea", label: "Pacific/Noumea (UTC+11:00)", city: "Noumea", offset: "UTC+11:00", region: "Pacific" },
  { value: "Pacific/Pago_Pago", label: "Pacific/Pago_Pago (UTC-11:00)", city: "Pago Pago", offset: "UTC-11:00", region: "Pacific" },
  { value: "Pacific/Palau", label: "Pacific/Palau (UTC+09:00)", city: "Palau", offset: "UTC+09:00", region: "Pacific" },
  { value: "Pacific/Pitcairn", label: "Pacific/Pitcairn (UTC-08:00)", city: "Pitcairn", offset: "UTC-08:00", region: "Pacific" },
  { value: "Pacific/Pohnpei", label: "Pacific/Pohnpei (UTC+11:00)", city: "Pohnpei", offset: "UTC+11:00", region: "Pacific" },
  { value: "Pacific/Port_Moresby", label: "Pacific/Port_Moresby (UTC+10:00)", city: "Port Moresby", offset: "UTC+10:00", region: "Pacific" },
  { value: "Pacific/Rarotonga", label: "Pacific/Rarotonga (UTC-10:00)", city: "Rarotonga", offset: "UTC-10:00", region: "Pacific" },
  { value: "Pacific/Saipan", label: "Pacific/Saipan (UTC+10:00)", city: "Saipan", offset: "UTC+10:00", region: "Pacific" },
  { value: "Pacific/Tahiti", label: "Pacific/Tahiti (UTC-10:00)", city: "Tahiti", offset: "UTC-10:00", region: "Pacific" },
  { value: "Pacific/Tarawa", label: "Pacific/Tarawa (UTC+12:00)", city: "Tarawa", offset: "UTC+12:00", region: "Pacific" },
  { value: "Pacific/Tongatapu", label: "Pacific/Tongatapu (UTC+13:00)", city: "Tongatapu", offset: "UTC+13:00", region: "Pacific" },
  { value: "Pacific/Wake", label: "Pacific/Wake (UTC+12:00)", city: "Wake", offset: "UTC+12:00", region: "Pacific" },
  { value: "Pacific/Wallis", label: "Pacific/Wallis (UTC+12:00)", city: "Wallis", offset: "UTC+12:00", region: "Pacific" },

  // UTC
  { value: "UTC", label: "UTC (UTC+00:00)", city: "UTC", offset: "UTC+00:00", region: "UTC" },
];

// Helper functions for searching and formatting
export const searchTimezones = (searchTerm: string): TimezoneOption[] => {
  if (!searchTerm) return timezoneOptions;
  
  const lowerSearch = searchTerm.toLowerCase();
  return timezoneOptions.filter(tz => 
    tz.city.toLowerCase().includes(lowerSearch) ||
    tz.region.toLowerCase().includes(lowerSearch) ||
    tz.value.toLowerCase().includes(lowerSearch) ||
    tz.offset.toLowerCase().includes(lowerSearch)
  );
};

export const getTimezoneByValue = (value: string): TimezoneOption | undefined => {
  return timezoneOptions.find(tz => tz.value === value);
};

export const formatTimezoneDisplay = (timezone: TimezoneOption | undefined): string => {
  if (!timezone) return "";
  return `${timezone.city} (${timezone.offset})`;
};
